language: generic
os: osx
osx_image: xcode6.4

script:
  - VERSION="2.7.14"
  - git clone https://github.com/matthew-brett/multibuild
  - source multibuild/osx_utils.sh
  - get_macpython_environment $VERSION
  - pip install --user numpy scipy
  - ${PYTHON_EXE} --version
  - ${PYTHON_EXE} -c 'import sys, scipy, numpy; print(scipy.__version__, numpy.__version__, sys.version_info)'
  - ${PYTHON_EXE} -c 'from scipy.optimize import fsolve'
