language: generic
os: osx
osx_image: xcode8.3

script:
  - set -ex
  - shell_session_update() { :; }
  # Workaround suggested by Thomas K at
  # https://github.com/travis-ci/travis-ci/issues/8703#issuecomment-347881274
  - unset -f cd
  - mkdir tmp_repos
  - cd tmp_repos
