# Set TEST_BUILDS=1 to run library_builders tests

language: generic

matrix:
  include:
    - os: osx
      osx_image: xcode8.3
      env:
        - PYTHON_VERSION=3.5

script:
  - set -x
  - source tests/test_multibuild.sh
