# Set TEST_BUILDS=1 to run library_builders tests

language: generic
os: osx
osx_image: xcode8.3

script:
  - set -x
  - set -e
  - shell_session_update() { :; }
  - mkdir tmp_repos
  - cd tmp_repos
  - mkdir project
